services:

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: messanger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #Хранилище данных, чтобы БД не стиралась при перезапуске

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:admin@db:5432/messanger
    depends_on:
      - db # Запускать FastAPI только ПОСЛЕ старта контейнера с базой
    volumes:
      - ./backend:/app


  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend # Точное имя сервиса бэкенда из блока выше

volumes:
  postgres_data: # Объявление виртуального диска Docker